"""
Direct-projection reproducibility analyses.

``dir_proj`` is the aggregate version (pairwise cross-group mean reproducibility);
``dir_proj_bypc`` is the per-component breakdown anchored against the pooled-data
PCA, with a tiled grid of per-component G×G heatmaps as its primary plot.
"""
from ..._deps import pd, np, randint, plt, StandardScaler

import os
import copy

from itertools import combinations

from ...core.base_pca import basePCA
from ...preprocessing.preliminary import _check_rank
from ...preprocessing.data_utils import group_standardize
from ...io.save import setupanalysis

from ..metrics import RHom
from ..resampling import pair_cv
from ..bootstrap import BootstrapEngine

from ._reporting import _build_row, _display_stats, _export_report, _chance_reference, _resolve_null_seed


def dir_proj(df=None, group=None, npc=None, method='svd', rotation="varimax", corr='pearson',
             folds=5, save=True, plot=True, display=False, null=True, null_reps=200, null_seed=None, cluster=None,
             groupby=None, subspace=False, progress=True, path='results', file_prefix=randint(10000, 99999)):
    """
    Direct-Projection Reproducibility
    ---------------------------------
    This function conducts a bootstrapped direct-projection analysis
    on your data based on some inputted grouping variable. This involves
    dividing each group into its own dataframe, and assessing the similarity
    of the components generated by each group to each other group based on:
        1) Loading similarity (with Tucker's Congruence Coefficient: Tucker, 1951; See also Lovik et al., 2020)
        2) Component-score similarity (with R-homologue: Mulholland et al., 2023; See also Everett, 1983)

    Parameters
    ----------

        df: pd.Dataframe, default=None
            It should include only the columns to be decomposed and your grouping variable.

        group: str, default=None
            The column heading for your grouping variable.

        cluster: str, default=None
            Optional level-2 / clustering column (e.g. participant ID). When provided,
            whole clusters are kept together in every resample, fold, and split, so a unit
            never appears on both sides of a comparison. Prevents leakage and
            pseudoreplication with nested data. Requires at least `folds` distinct clusters
            per group where cross-validation is used.

        groupby: str, default=None
            Optional nuisance-grouping column for groupedPCA-style decomposition: each
            variable is z-scored within each level of this column before decomposing
            (per resample, on its own rows -- leakage-free), so the analysis
            characterizes a grouped solution. Independent of ``group``, and typically a
            *separate* nuisance grouping: with ``groupby=group`` the per-group loadings
            are unchanged (each pairwise comparison is already computed within a single
            group), so it is not a meaningful setting for this analysis.

        subspace: bool, default=False
            If True, also report subspace similarity via principal angles between the two
            loading subspaces (sub_* columns; rotation- and order-invariant, in [0, 1]).

        corr: str, default="pearson"
            Which correlation matrix to decompose under `method='eigen'`: "pearson",
            "spearman" (rank correlation, ordinal-friendly), or "polychoric" (latent
            correlation behind ordinal items via Olsson 1979 MLE; meaningful only for
            genuinely ordinal data and noticeably slower). Ignored under `method='svd'`,
            which is Pearson-only; pass `method='eigen'` to switch correlation type.

        npc: int, default=None
            Number of components to extract per solution.

        rotation: str, default="varimax"
            Rotation method to be performed on referent. "none" for no rotation.

        folds: int, default=5
            Number of folds to use for cross-validation.

        save: bool, default=True
            Save outputted reproducibility results to .csv.

        plot: bool, default=True
            Visualise results with heatmaps.

        display: bool, default=False
            Print output in the terminal.

        null: bool, default=True
            If True, estimate the chance level by permutation (Mantel-shuffle the
            features, compare two PCAs) and attach it to ``df.attrs["null"]``. The heatmap
            then centres its colour scale on chance and annotates the chance level + CI.
            The null projects onto the shuffled loadings, so both sides of the comparison
            come from the same null world (the observed analysis projects onto real data).

        null_reps: int, default=200
            Number of shuffled permutation draws used to estimate the chance level.

        null_seed: int, optional
            Seed for the permutation RNG. When omitted, a fresh random seed is drawn per
            call; either way the seed actually used is recorded in ``df.attrs["null_seed"]``,
            so the chance level + CI (and the band drawn on the figure) can be reproduced
            later by passing it back as ``null_seed=``.

        path: str, default='results'
            The path to the output directory.

        file_prefix: str, default=randint(10000,99999)
            Provide name to distinguish saved files. By default will classify files with random 5-digit ID.

    Returns
    -------
        pd.DataFrame:
            The function at minimum returns a pandas dataframe with the results.

        .csv:
            If save=True, will save a .csv file to /results.

        .png:
            If plot=True, will save heatmaps for loading similarity and component-score similarity.

        printed results:
            If display=True, prints the output directly in the terminal.
    """

    groups = df[group].unique()
    # maindict retains the cluster (and groupby) column so folds can keep whole units
    # together and group-standardize per fold; both are stripped from the decomposition
    # inside pair_cv._make_folds / _prep.
    maindict = {g: df[df[group] == g].drop(labels=group, axis=1) for g in groups}
    pairings = list(combinations(groups, 2))

    feat_cols = df.columns.drop([c for c in (group, cluster, groupby) if c is not None])
    scaler = StandardScaler()
    df_scaled = pd.DataFrame(scaler.fit_transform(df[feat_cols]), columns=feat_cols)
    _check_rank(df_scaled)

    # R-homologue projection target: group-standardized (full data) under groupby so it
    # matches the within-group component space; globally scaled features otherwise.
    rd_src = (group_standardize(df, groupby, feature_cols=list(feat_cols))[list(feat_cols)].values
              if groupby else df_scaled.values)
    boot_model = RHom(rd=copy.deepcopy(rd_src), n_comp=npc,
                      method=method, rotation=rotation, corr=corr)
    cv = pair_cv(boot=True, k=folds, cluster=cluster, groupby=groupby)

    boot_engine = BootstrapEngine(
        estimator=boot_model,
        cv=cv,
        pro_cong=True,
        shuffle=False,
        subspace=subspace,
        progress=progress,
        progress_desc="Direct-projection CV",
    )

    rows = []
    for ref, comp in pairings:
        print(f"Running {ref} x {comp}")

        _check_rank(maindict[ref][feat_cols])
        _check_rank(maindict[comp][feat_cols])
        # Execute using referent and comparator subsets
        results = boot_engine(X=maindict[ref], y=maindict[comp], group=group)

        meta = {'referent': ref, 'comparator': comp}
        row = _build_row(boot_model.n_comp, results[0], results[1],
                         sub_data=results[2] if subspace else None, metadata=meta)
        rows.append(row)

        if display:
            _display_stats(f"Direct Projection: {ref} x {comp}", row)

    dirproj_df = pd.DataFrame(rows)

    # Chance reference: similarity of two PCAs of Mantel-shuffled (structure-free) data.
    null_ref = None
    if null:
        null_seed = _resolve_null_seed(null_seed)
        null_ref = _chance_reference(df[feat_cols], npc, method, rotation, corr, subspace,
                                     null_reps, progress, desc="Chance null (dir-proj)",
                                     groupby_labels=(df[groupby].values if groupby else None),
                                     group_labels=df[group].values, seed=null_seed)
        dirproj_df.attrs["null"] = null_ref
        dirproj_df.attrs["null_reps"] = null_reps
        dirproj_df.attrs["null_seed"] = null_seed

    if plot:
        from ...visualization.rhomplots import plot_dirproj
        setupanalysis(path, file_prefix, includetime=False)
        plt.close('all')

        metrics = ["rhm", "phi"] + (["sub"] if subspace else [])
        for name in metrics:
            fig = plot_dirproj(dirproj_df, metric=name, null=null_ref)
            fig.savefig(
                os.path.join(path, f"{file_prefix}/{file_prefix}_heatmap{len(df_scaled.columns)}D_{npc}PC_{name}.png"),
                bbox_inches="tight",
                dpi=150,
            )
            # plt.show()
            plt.close(fig)

    if save:
        _export_report(dirproj_df, path, file_prefix, f"dj{len(df_scaled.columns)}D_{npc}PC")

    return dirproj_df


def dir_proj_bypc(df=None, group=None, npc=None, method='svd', rotation="varimax", corr='pearson',
                  folds=5, save=True, plot=True, display=False, null=True, null_reps=200, null_seed=None, cluster=None,
                  groupby=None, subspace=False, progress=True, path='results', file_prefix=randint(10000, 99999)):
    """
    Direct-Projection Reproducibility: By-Component
    -----------------------------------------------
    Pairwise direct-projection reproducibility broken down per component. A pooled-data
    PCA on the full dataset defines a canonical PC1..PC{npc} frame; every per-fold PCA
    in each pair is Procrustes-aligned to that anchor before scoring, so column index k
    refers to the same homologue across all (referent, comparator, replicate) triples.
    This is the bootstrapped analogue of the one-shot bypc heatmaps in the example
    script, and the dir_proj counterpart of `bypc` (which anchors against an omnibus
    half-sample rather than a pooled fit).

    Reports component similarity with:
        1) Loading similarity (Tucker's Congruence Coefficient: Tucker, 1951; See also Lovik et al., 2020)
        2) Component-score similarity (R-homologue: Mulholland et al., 2023; See also Everett, 1983)

    Parameters
    ----------

        df: pd.Dataframe, default=None
            It should include only the columns to be decomposed and your grouping variable.

        group: str, default=None
            The column heading for your grouping variable.

        cluster: str, default=None
            Optional level-2 / clustering column (e.g. participant ID). When provided,
            whole clusters are kept together in every resample, fold, and split, so a unit
            never appears on both sides of a comparison. Prevents leakage and
            pseudoreplication with nested data. Requires at least `folds` distinct clusters
            per group.

        groupby: str, default=None
            Optional nuisance-grouping column for groupedPCA-style decomposition: each
            variable is z-scored within each level of this column before decomposing
            (per resample, on its own rows -- leakage-free), so the analysis
            characterizes a grouped solution. Independent of ``group``, and typically a
            *separate* nuisance grouping: with ``groupby=group`` the per-group loadings
            are unchanged (each pairwise comparison is already computed within a single
            group), so it is not a meaningful setting for this analysis.

        subspace: bool, default=False
            If True, also report subspace similarity via principal angles between the two
            loading subspaces. Subspace similarity is a whole-solution property, so the
            per-pair value is broadcast across the npc rows for that pair.

        corr: str, default="pearson"
            Which correlation matrix to decompose under `method='eigen'`: "pearson",
            "spearman" (rank correlation, ordinal-friendly), or "polychoric" (latent
            correlation behind ordinal items via Olsson 1979 MLE; meaningful only for
            genuinely ordinal data and noticeably slower). Ignored under `method='svd'`,
            which is Pearson-only; pass `method='eigen'` to switch correlation type.

        npc: int, default=None
            Number of components to extract per solution.

        rotation: str, default="varimax"
            Rotation method applied to the anchor PCA. "none" for no rotation.

        folds: int, default=5
            Number of folds to use for cross-validation within each pair.

        save: bool, default=True
            Save outputted reproducibility results to .csv.

        plot: bool, default=True
            Visualise results as a grid of per-component pairwise heatmaps.

        display: bool, default=False
            Print output in the terminal.

        null: bool, default=True
            If True, estimate the chance level by permutation (Mantel-shuffle the
            features, compare two PCAs) and attach it to ``df.attrs["null"]``. The heatmap
            then centres its colour scale on chance and annotates the chance level + CI.
            The null projects onto the shuffled loadings, so both sides of the comparison
            come from the same null world (the observed analysis projects onto real data).

        null_reps: int, default=200
            Number of shuffled permutation draws used to estimate the chance level.

        null_seed: int, optional
            Seed for the permutation RNG. When omitted, a fresh random seed is drawn per
            call; either way the seed actually used is recorded in ``df.attrs["null_seed"]``,
            so the chance level + CI (and the band drawn on the figure) can be reproduced
            later by passing it back as ``null_seed=``.

        path: str, default='results'
            The path to the output directory.

        file_prefix: str, default=randint(10000,99999)
            Provide name to distinguish saved files. By default will classify files with random 5-digit ID.

    Returns
    -------
        pd.DataFrame:
            One row per (referent, comparator, comp) triple, with rhm_*, phi_*, and
            optional sub_* summary columns.

        .csv:
            If save=True, will save the results dataframe to /results.

        .png:
            If plot=True, saves a tiled grid of npc heatmaps per metric.

        printed results:
            If display=True, prints per-component results in the terminal.
    """

    groups = df[group].unique()
    maindict = {g: df[df[group] == g].drop(labels=group, axis=1) for g in groups}
    pairings = list(combinations(groups, 2))

    feat_cols = df.columns.drop([c for c in (group, cluster, groupby) if c is not None])
    scaler = StandardScaler()
    df_scaled = pd.DataFrame(scaler.fit_transform(df[feat_cols]), columns=feat_cols)
    _check_rank(df_scaled)

    # Global anchor: pooled-data PCA defines the canonical PC1..PC{npc} homologue. Every
    # per-fold PCA inside the bootstrap is Procrustes-aligned to this anchor (handled by
    # rhom when `anchor=` is set), so the bypc column index carries a consistent meaning
    # across all replicates and pairs. Under groupby the anchor is itself a grouped
    # (within-group standardized) pooled solution.
    anchor_input = (group_standardize(df, groupby, feature_cols=list(feat_cols))[list(feat_cols)]
                    if groupby else df_scaled)
    anchor_pca = basePCA(n_components=npc, rotation=rotation, method=method, corr=corr)
    anchor_pca.fit(anchor_input)
    anchor_loadings = anchor_pca.loadings.to_numpy()

    rd_src = anchor_input.values if groupby else df_scaled.values
    boot_model = RHom(rd=copy.deepcopy(rd_src), bypc=True, n_comp=npc,
                      method=method, rotation=rotation, corr=corr,
                      anchor=anchor_loadings)
    cv = pair_cv(boot=True, k=folds, cluster=cluster, groupby=groupby)

    # mode=None means cv.split is used (symmetric two-sided fold cross like dir_proj).
    # per_component=True makes the engine transpose the score / phi accumulators into
    # [npc × n_replicates] lists at the end and collapse the per-direction subspace
    # cosines to per-replicate means -- so we don't have to do that work here.
    boot_engine = BootstrapEngine(
        estimator=boot_model,
        cv=cv,
        per_component=True,
        pro_cong=True,
        shuffle=False,
        subspace=subspace,
        progress=progress,
        progress_desc="Direct-projection bypc CV",
    )

    rows = []
    for ref, comp in pairings:
        print(f"Running By-Component Direct Projection: {ref} x {comp}")

        _check_rank(maindict[ref][feat_cols])
        _check_rank(maindict[comp][feat_cols])

        results = boot_engine(X=maindict[ref], y=maindict[comp], group=group)
        # results layout with per_component=True (engine handles transpose + subspace collapse):
        #   results[0]: list-of-lists [npc × n_replicates]  -- |r| per component per replicate
        #   results[1]: list-of-lists [npc × n_replicates]  -- TCC per component per replicate
        #   results[2]: list of floats  [n_replicates]      -- per-replicate mean subspace cosine

        rhm_per_comp = results[0]
        phi_per_comp = results[1]
        sub_per_pair = results[2] if subspace else None

        for idx in range(npc):
            meta = {'referent': ref, 'comparator': comp, 'comp': idx + 1}
            row = _build_row(boot_model.n_comp, rhm_per_comp[idx], phi_per_comp[idx],
                             sub_data=sub_per_pair, metadata=meta)
            rows.append(row)

            if display:
                _display_stats(f"Direct Projection: {ref} x {comp} - Component {idx + 1}", row)

    dirproj_bypc_df = pd.DataFrame(rows)

    # Chance reference (single floor; under permutation per-component chance is uniform).
    null_ref = None
    if null:
        null_seed = _resolve_null_seed(null_seed)
        null_ref = _chance_reference(df[feat_cols], npc, method, rotation, corr, subspace,
                                     null_reps, progress, desc="Chance null (dir-proj bypc)",
                                     groupby_labels=(df[groupby].values if groupby else None),
                                     group_labels=df[group].values,
                                     anchor=anchor_loadings, bypc=True, seed=null_seed)
        dirproj_bypc_df.attrs["null"] = null_ref
        dirproj_bypc_df.attrs["null_reps"] = null_reps
        dirproj_bypc_df.attrs["null_seed"] = null_seed

    if plot:
        # Persist anchor loadings alongside the stats CSV and attach to the returned
        # frame so plot_dirproj_bypc can label panels with PC identity if desired.
        dirproj_bypc_df.attrs["loadings"] = anchor_pca.loadings.copy()

        from ...visualization.rhomplots import plot_dirproj_bypc, plot_aligned_wordclouds
        setupanalysis(path, file_prefix, includetime=False)
        plt.close('all')

        # Per-group full-data PCA -- one PCA per group on the group's entire data
        # (not a bootstrap fold). plot_aligned_wordclouds then Procrustes-aligns each
        # to the global anchor before rendering, so column k in every group's row
        # refers to the same homologue defined by the pooled reference. Under groupby
        # each group's PCA is itself a within-group-standardized (grouped) solution.
        def _group_fit_input(g):
            sub = maindict[g]
            if groupby:
                return group_standardize(sub, groupby, feature_cols=list(feat_cols))[list(feat_cols)]
            return sub[feat_cols]

        group_loadings = {
            g: basePCA(n_components=npc, rotation=rotation,
                       method=method, corr=corr).fit(_group_fit_input(g)).loadings
            for g in groups
        }
        wc_fig = plot_aligned_wordclouds(
            group_loadings,
            anchor_loadings=anchor_pca.loadings,
            n_features=len(df_scaled.columns),
            show_var=True,
            title="Per-group components (Procrustes-aligned to pooled reference)",
        )
        wc_fig.savefig(
            os.path.join(path, f"{file_prefix}/{file_prefix}_dj_bypc_wordclouds_{len(df_scaled.columns)}D_{npc}PC.png"),
            bbox_inches="tight", dpi=150,
        )
        # plt.show()
        plt.close(wc_fig)

        metrics = ["rhm", "phi"] + (["sub"] if subspace else [])
        for name in metrics:
            fig = plot_dirproj_bypc(dirproj_bypc_df, metric=name, null=null_ref)
            fig.savefig(
                os.path.join(path, f"{file_prefix}/{file_prefix}_dj_bypc_{len(df_scaled.columns)}D_{npc}PC_{name}.png"),
                bbox_inches="tight", dpi=150,
            )
            # plt.show()
            plt.close(fig)

        loadings_path = os.path.join(
            path, f"{file_prefix}",
            f"{file_prefix}_loadings_{len(df_scaled.columns)}D_{npc}PC.csv",
        )
        anchor_pca.loadings.to_csv(loadings_path)

    if save:
        _export_report(dirproj_bypc_df, path, file_prefix,
                       f"dj_bypc_{len(df_scaled.columns)}D_{npc}PC")

    return dirproj_bypc_df
