[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RHom"
version = "0.1.0"
description = "Reliability and generalizability analyses in PCA"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Louis Chitiz", email = "louischitiz@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]


dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "seaborn",
    "matplotlib",
    "scikit-learn",
    "adjustText",
    "wordcloud",
    "factor_analyzer"
]

[tool.setuptools.packages.find]
where = ["src"]